coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
        only_pulls: true
ignore:
  - target
  - website
  - resources
  - docs
