[package]
name = "avnu"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.11.4"

[dependencies]
starknet = "2.9.1"
avnu_lib = { git = "https://github.com/avnu-labs/avnu-contracts-lib", tag = "v0.1.0" }

[dev-dependencies]
cairo_test = "2.11.4"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 140
