[package]
name = "paymaster-client"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
paymaster-rpc = { path = "../paymaster-rpc" }
paymaster-starknet = { path = "../paymaster-starknet" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }
starknet = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock = { workspace = true }
