name: Tests and linter

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2

      # Check
      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      # Format
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # Build
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

  # Test
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust env
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
          toolchain: stable
      - name: Retreive cached dependecies
        uses: Swatinem/rust-cache@v2
      - name: Setup coverage env
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info